-- LOFI Artist Intelligence — Supabase schema reference
--
-- NOTE: This file is a reference only. The live schema is in the `tinder` Postgres
-- schema on Supabase and should not be recreated from this file.
--
-- To inspect the real schema:
--   1. Supabase dashboard → Table Editor → switch schema to `tinder`
--   2. Or: SELECT table_name FROM information_schema.tables WHERE table_schema = 'tinder';
--
-- Key tables (all in tinder.*):
--   artist_chartmetric_flat   — flat current metrics per artist (primary dashboard table)
--   artist_chartmetric        — timeseries JSONB + ml_features
--   artist_cm_extended        — rich CM data: demographics, playlists, tracks, milestones
--   artist_cm_playlists       — editorial playlist placements
--   artist_cm_tracks          — top tracks per artist
--   artist_chartmetric_scores — nightly score history (5 scores)
--   artist_ra                 — RA event history (events JSONB)
--   ra_events                 — normalised RA event rows
--   artist_partyflock         — Partyflock NL data + events JSONB
--   artist_lastfm             — Last.fm tags, listeners, playcount
--   validation_events         — career milestones (first_ibiza, first_boiler_room, etc.)
--   xgboost_predictions       — ML model output: predicted_growth_90d
--   youtube_sets              — scraped YouTube videos with velocity + trending flag
--   youtube_snapshots         — view count snapshots for velocity computation
--   youtube_channels          — channel registry
--   beatport_chart_entries    — Beatport top 100 positions
--   ra_podcast_appearances    — RA Podcast episode appearances
--   bbc_radio1_appearances    — BBC Essential Mix appearances
--   discovery_queue           — unknown artists found in trending content
--   artist_embeddings         — feature vectors for similarity search
--
-- Primary key: artist_id (UUID) links all tables.
-- Migration history: Supabase dashboard → Database → Migrations
